USE summersync
insert into Activity (activityID, name, description) values (1, 'Hiking', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into Activity (activityID, name, description) values (2, 'Archery', 'Nullam porttitor lacus at turpis.');
insert into Activity (activityID, name, description) values (3, 'Swimming', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into Activity (activityID, name, description) values (4, 'Canoeing', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Activity (activityID, name, description) values (5, 'Kayaking', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Activity (activityID, name, description) values (6, 'Rock climbing', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into Activity (activityID, name, description) values (7, 'Zip-lining', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into Activity (activityID, name, description) values (8, 'Arts and crafts', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
insert into Activity (activityID, name, description) values (9, 'Nature walks', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into Activity (activityID, name, description) values (10, 'Campfire storytelling', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into Activity (activityID, name, description) values (11, 'Orienteering', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into Activity (activityID, name, description) values (12, 'Horseback riding', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into Activity (activityID, name, description) values (13, 'Fishing', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into Activity (activityID, name, description) values (14, 'Birdwatching', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Activity (activityID, name, description) values (15, 'Soccer', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into Activity (activityID, name, description) values (16, 'Scavenger hunts', 'Vestibulum rutrum rutrum neque.');
insert into Activity (activityID, name, description) values (17, 'Talent shows', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Activity (activityID, name, description) values (18, 'Outdoor cooking', 'Proin risus.');
insert into Activity (activityID, name, description) values (19, 'Survival skills training', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Activity (activityID, name, description) values (20, 'Star gazing', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into Activity (activityID, name, description) values (21, 'Dance parties', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.');
insert into Activity (activityID, name, description) values (22, 'Capture the flag', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Activity (activityID, name, description) values (23, 'Relay races', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Activity (activityID, name, description) values (24, 'Yoga', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into Activity (activityID, name, description) values (25, 'Meditation', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
insert into Activity (activityID, name, description) values (26, 'Gardening', 'Suspendisse potenti. In eleifend quam a odio.');
insert into Activity (activityID, name, description) values (27, 'Environmental education', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Activity (activityID, name, description) values (28, 'Drama/Improv games', 'In hac habitasse platea dictumst.');
insert into Activity (activityID, name, description) values (29, 'Music workshops', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Activity (activityID, name, description) values (30, 'Photography', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into Activity (activityID, name, description) values (31, 'Pottery', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Activity (activityID, name, description) values (32, 'Mountain biking', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into Activity (activityID, name, description) values (33, 'High ropes course', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into Activity (activityID, name, description) values (34, 'Low ropes course', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into Activity (activityID, name, description) values (35, 'Sailing', 'Nulla mollis molestie lorem.');
insert into Activity (activityID, name, description) values (36, 'Paddleboarding', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into Activity (activityID, name, description) values (37, 'Slip and slide', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into Activity (activityID, name, description) values (38, 'Campout under the stars', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Activity (activityID, name, description) values (39, 'Tie-dyeing', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into Activity (activityID, name, description) values (40, 'Animal tracking', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
