insert into Cabin (cabinID, cabinName, staffID, capacity) values (1, 'Red-billed buffalo weaver', '1', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (2, 'Elephant, asian', '33', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (3, 'Goliath heron', '40', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (4, 'Blue-footed booby', '23', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (5, 'Badger, american', '21', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (6, 'Spotted wood sandpiper', '3', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (7, 'Pied cormorant', '4', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (8, 'Gull, swallow-tail', '22', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (9, 'Kalahari scrub robin', '14', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (10, 'Topi', '27', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (11, 'Yellow-billed stork', '25', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (12, 'Black-throated butcher bird', '19', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (13, 'Ring-tailed lemur', '16', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (14, 'Frogmouth, tawny', '20', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (15, 'Australian brush turkey', '8', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (16, 'White-headed vulture', '24', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (17, 'Trumpeter, dark-winged', '9', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (18, 'Tortoise, burmese brown mountain', '7', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (19, 'Bushpig', '12', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (20, 'Golden brush-tailed possum', '18', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (21, 'Asian water buffalo', '35', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (22, 'Grenadier, common', '32', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (23, 'Stork, black-necked', '34', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (24, 'Caracara (unidentified)', '31', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (25, 'Insect, stick', '38', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (26, 'Wagtail, african pied', '17', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (27, 'Black-collared barbet', '15', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (28, 'Squirrel, richardson''s ground', '37', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (29, 'Gull, kelp', '13', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (30, 'Squirrel, palm', '10', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (31, 'Ant (unidentified)', '39', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (32, 'Black-collared barbet', '30', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (33, 'Dove, mourning collared', '11', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (34, 'Brown capuchin', '6', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (35, 'Mocking cliffchat', '28', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (36, 'Bird (unidentified)', '36', 6);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (37, 'Goose, canada', '5', 8);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (38, 'Scaly-breasted lorikeet', '26', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (39, 'Dragon, asian water', '2', 10);
insert into Cabin (cabinID, cabinName, staffID, capacity) values (40, 'Woodrat (unidentified)', '29', 10);
