USE summersync
insert into Location (locationID, region, territory, adminID) values (1, 'Minnesota', 'Minneapolis', '22');
insert into Location (locationID, region, territory, adminID) values (2, 'Connecticut', 'New Haven', '32');
insert into Location (locationID, region, territory, adminID) values (3, 'Florida', 'Homestead', '11');
insert into Location (locationID, region, territory, adminID) values (4, 'Illinois', 'Chicago', '4');
insert into Location (locationID, region, territory, adminID) values (5, 'Rhode Island', 'Providence', '23');
insert into Location (locationID, region, territory, adminID) values (6, 'Georgia', 'Atlanta', '36');
insert into Location (locationID, region, territory, adminID) values (7, 'Alabama', 'Montgomery', '24');
insert into Location (locationID, region, territory, adminID) values (8, 'Texas', 'Houston', '17');
insert into Location (locationID, region, territory, adminID) values (9, 'Virginia', 'Newport News', '25');
insert into Location (locationID, region, territory, adminID) values (10, 'South Carolina', 'Beaufort', '5');
insert into Location (locationID, region, territory, adminID) values (11, 'New York', 'Brooklyn', '18');
insert into Location (locationID, region, territory, adminID) values (12, 'Pennsylvania', 'Harrisburg', '16');
insert into Location (locationID, region, territory, adminID) values (13, 'Ohio', 'Akron', '3');
insert into Location (locationID, region, territory, adminID) values (14, 'California', 'Fresno', '19');
insert into Location (locationID, region, territory, adminID) values (15, 'Texas', 'Houston', '7');
insert into Location (locationID, region, territory, adminID) values (16, 'Michigan', 'Saginaw', '30');
insert into Location (locationID, region, territory, adminID) values (17, 'Alabama', 'Huntsville', '28');
insert into Location (locationID, region, territory, adminID) values (18, 'Pennsylvania', 'New Castle', '8');
insert into Location (locationID, region, territory, adminID) values (19, 'Ohio', 'Columbus', '10');
insert into Location (locationID, region, territory, adminID) values (20, 'Minnesota', 'Minneapolis', '2');
insert into Location (locationID, region, territory, adminID) values (21, 'Iowa', 'Des Moines', '38');
insert into Location (locationID, region, territory, adminID) values (22, 'Washington', 'Vancouver', '29');
insert into Location (locationID, region, territory, adminID) values (23, 'Missouri', 'Springfield', '33');
insert into Location (locationID, region, territory, adminID) values (24, 'Missouri', 'Kansas City', '40');
insert into Location (locationID, region, territory, adminID) values (25, 'Florida', 'Orlando', '15');
insert into Location (locationID, region, territory, adminID) values (26, 'South Carolina', 'Columbia', '34');
insert into Location (locationID, region, territory, adminID) values (27, 'Alabama', 'Birmingham', '1');
insert into Location (locationID, region, territory, adminID) values (28, 'California', 'Los Angeles', '12');
insert into Location (locationID, region, territory, adminID) values (29, 'Florida', 'Clearwater', '9');
insert into Location (locationID, region, territory, adminID) values (30, 'Alabama', 'Birmingham', '6');
insert into Location (locationID, region, territory, adminID) values (31, 'Pennsylvania', 'Reading', '26');
insert into Location (locationID, region, territory, adminID) values (32, 'New Jersey', 'Paterson', '13');
insert into Location (locationID, region, territory, adminID) values (33, 'Missouri', 'Columbia', '21');
insert into Location (locationID, region, territory, adminID) values (34, 'New York', 'Brooklyn', '37');
insert into Location (locationID, region, territory, adminID) values (35, 'Texas', 'Dallas', '14');
insert into Location (locationID, region, territory, adminID) values (36, 'Pennsylvania', 'Pittsburgh', '27');
insert into Location (locationID, region, territory, adminID) values (37, 'Ohio', 'Dayton', '31');
insert into Location (locationID, region, territory, adminID) values (38, 'Georgia', 'Columbus', '35');
insert into Location (locationID, region, territory, adminID) values (39, 'West Virginia', 'Morgantown', '20');
insert into Location (locationID, region, territory, adminID) values (40, 'Massachusetts', 'New Bedford', '39');
