USE summersync
insert into MedicalInfo (medID, type) values (1, 'Peanut allergy');
insert into MedicalInfo (medID, type) values (2, 'Tree nut allergy');
insert into MedicalInfo (medID, type) values (3, 'Dairy allergy');
insert into MedicalInfo (medID, type) values (4, 'Egg allergy');
insert into MedicalInfo (medID, type) values (5, 'Soy allergy');
insert into MedicalInfo (medID, type) values (6, 'Wheat allergy');
insert into MedicalInfo (medID, type) values (7, 'Shellfish allergy');
insert into MedicalInfo (medID, type) values (8, 'Fish allergy');
insert into MedicalInfo (medID, type) values (9, 'Gluten intolerance/Celiac disease');
insert into MedicalInfo (medID, type) values (10, 'Sesame allergy');
insert into MedicalInfo (medID, type) values (11, 'Corn allergy');
insert into MedicalInfo (medID, type) values (12, 'Mustard allergy');
insert into MedicalInfo (medID, type) values (13, 'Lactose intolerance');
insert into MedicalInfo (medID, type) values (14, 'Vegan diet');
insert into MedicalInfo (medID, type) values (15, 'Vegetarian diet');
insert into MedicalInfo (medID, type) values (16, 'Halal diet');
insert into MedicalInfo (medID, type) values (17, 'Kosher diet');
insert into MedicalInfo (medID, type) values (18, 'Low-sodium diet');
insert into MedicalInfo (medID, type) values (19, 'Low-sugar/Diabetic diet');
insert into MedicalInfo (medID, type) values (20, 'High-protein diet');
insert into MedicalInfo (medID, type) values (21, 'FODMAP diet');
insert into MedicalInfo (medID, type) values (22, 'Keto diet');
insert into MedicalInfo (medID, type) values (23, 'Nut-free diet');
insert into MedicalInfo (medID, type) values (24, 'Asthma');
insert into MedicalInfo (medID, type) values (25, 'Type 1 Diabetes');
insert into MedicalInfo (medID, type) values (26, 'Epilepsy');
insert into MedicalInfo (medID, type) values (27, 'Attention Deficit Hyperactivity Disorder (ADHD)');
insert into MedicalInfo (medID, type) values (28, 'Autism Spectrum Disorder (ASD)');
insert into MedicalInfo (medID, type) values (29, 'Anxiety disorders');
insert into MedicalInfo (medID, type) values (30, 'Depression');
insert into MedicalInfo (medID, type) values (31, 'Cerebral palsy');
insert into MedicalInfo (medID, type) values (32, 'Down syndrome');
insert into MedicalInfo (medID, type) values (33, 'Hemophilia');
insert into MedicalInfo (medID, type) values (34, 'Juvenile rheumatoid arthritis');
insert into MedicalInfo (medID, type) values (35, 'Congenital heart defects');
insert into MedicalInfo (medID, type) values (36, 'Cystic fibrosis');
insert into MedicalInfo (medID, type) values (37, 'Sickle cell anemia');
insert into MedicalInfo (medID, type) values (38, 'Eczema');
insert into MedicalInfo (medID, type) values (39, 'Food protein-induced enterocolitis syndrome (FPIES)');
insert into MedicalInfo (medID, type) values (40, 'Migraines');
