USE summersync
insert into RequiredItems (requiredItems, activityID) values ('Walking stick', '32');
insert into RequiredItems (requiredItems, activityID) values ('Sunglasses sunscreen hat', '1');
insert into RequiredItems (requiredItems, activityID) values ('Playing cards board game', '26');
insert into RequiredItems (requiredItems, activityID) values ('Laundry bag detergent', '10');
insert into RequiredItems (requiredItems, activityID) values ('Binoculars bird guide', '4');
insert into RequiredItems (requiredItems, activityID) values ('Firewood matches', '31');
insert into RequiredItems (requiredItems, activityID) values ('Travel pillow eye mask', '18');
insert into RequiredItems (requiredItems, activityID) values ('hiking boots', '19');
insert into RequiredItems (requiredItems, activityID) values ('Firewood matches', '21');
insert into RequiredItems (requiredItems, activityID) values ('Binoculars bird guide', '12');
insert into RequiredItems (requiredItems, activityID) values ('Folding chair', '39');
insert into RequiredItems (requiredItems, activityID) values ('flashlights', '29');
insert into RequiredItems (requiredItems, activityID) values ('First aid kit', '38');
insert into RequiredItems (requiredItems, activityID) values ('Tent sleeping bag ground mat', '5');
insert into RequiredItems (requiredItems, activityID) values ('Helmet gloves', '40');
insert into RequiredItems (requiredItems, activityID) values ('s''mores ingredients', '27');
insert into RequiredItems (requiredItems, activityID) values ('First aid kit', '20');
insert into RequiredItems (requiredItems, activityID) values ('Hand sanitizer wipes', '9');
insert into RequiredItems (requiredItems, activityID) values ('First aid kit', '36');
insert into RequiredItems (requiredItems, activityID) values ('Portable charger charging cable', '30');
insert into RequiredItems (requiredItems, activityID) values ('marshmallows', '34');
insert into RequiredItems (requiredItems, activityID) values ('Yoga mat', '11');
insert into RequiredItems (requiredItems, activityID) values ('Yoga mat', '35');
insert into RequiredItems (requiredItems, activityID) values ('Rope carabiner harness', '22');
insert into RequiredItems (requiredItems, activityID) values ('Art supplies sketchpad', '6');
insert into RequiredItems (requiredItems, activityID) values ('bug spray', '13');
insert into RequiredItems (requiredItems, activityID) values ('Portable grill charcoal', '16');
insert into RequiredItems (requiredItems, activityID) values ('hiking boots', '7');
insert into RequiredItems (requiredItems, activityID) values ('Binoculars bird guide', '24');
insert into RequiredItems (requiredItems, activityID) values ('Travel pillow eye mask', '23');
insert into RequiredItems (requiredItems, activityID) values ('s''mores ingredients', '25');
insert into RequiredItems (requiredItems, activityID) values ('Laundry bag detergent', '3');
insert into RequiredItems (requiredItems, activityID) values ('Lantern fuel', '28');
insert into RequiredItems (requiredItems, activityID) values ('Sunscreen lip balmfishing rods', '33');
insert into RequiredItems (requiredItems, activityID) values ('Swimsuit towel', '14');
insert into RequiredItems (requiredItems, activityID) values ('Portable charger charging cable', '17');
insert into RequiredItems (requiredItems, activityID) values ('Folding chair', '15');
insert into RequiredItems (requiredItems, activityID) values ('Picnic blanket picnic basket', '37');
insert into RequiredItems (requiredItems, activityID) values ('Walking stick', '2');
insert into RequiredItems (requiredItems, activityID) values ('Art supplies sketchpad', '8');
