insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (1, 'Krishna', 'Peckham', 'Camp Director', '879-805-9007', 'kpeckham0@camp.com', '38', '40');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (2, 'Jacenta', 'Ruddock', 'Nature Guide', '212-146-8254', 'jruddock1@camp.com', '10', '13');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (3, 'Kevina', 'McKeefry', 'Activity Leader', '709-152-1460', 'kmckeefry2@camp.com', '8', '19');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (4, 'Arlyn', 'Ratnage', 'Camp Photographer', '200-100-6064', 'aratnage3@camp.com', '49', '30');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (5, 'Temple', 'Carrol', 'Camp Counselor', '164-641-1693', 'tcarrol4@camp.com', '6', '38');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (6, 'Rica', 'Polendine', 'Camp Counselor', '547-705-2752', 'rpolendine5@camp.com', '23', '38');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (7, 'Clarissa', 'Farey', 'Arts and Crafts Instructor', '587-287-3643', 'cfarey6@camp.com', '2', '15');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (8, 'Kort', 'Fallanche', 'Camp Photographer', '174-851-1813', 'kfallanche7@camp.com', '50', '37');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (9, 'Mill', 'Osgood', 'Camp Photographer', '761-328-9790', 'mosgood8@camp.com', '40', '14');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (10, 'Joice', 'Aberchirder', 'Activity Leader', '949-556-6785', 'jaberchirder9@camp.com', '3', '23');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (11, 'Ethyl', 'Allflatt', 'Camp Photographer', '875-849-8349', 'eallflatta@camp.com', '5', '39');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (12, 'Angelia', 'Dilawey', 'Camp Director', '935-197-5146', 'adilaweyb@camp.com', '17', '10');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (13, 'Nicol', 'Abrahamsohn', 'Camp Nurse', '926-876-5290', 'nabrahamsohnc@camp.com', '47', '18');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (14, 'Ron', 'Spering', 'Camp Photographer', '516-760-8824', 'rsperingd@camp.com', '20', '32');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (15, 'Towney', 'Hobgen', 'Nature Guide', '192-451-5706', 'thobgene@camp.com', '37', '16');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (16, 'Clarey', 'Wildt', 'Kitchen Staff', '530-540-9430', 'cwildtf@camp.com', '25', '24');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (17, 'Marrilee', 'Sleith', 'Outdoor Adventure Specialist', '699-873-8090', 'msleithg@camp.com', '9', '1');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (18, 'Jerrilyn', 'Mosey', 'Outdoor Adventure Specialist', '517-841-7392', 'jmoseyh@camp.com', '39', '32');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (19, 'Jordan', 'Chilvers', 'Lifeguard', '603-961-9363', 'jchilversi@camp.com', '29', '38');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (20, 'Mahalia', 'Clashe', 'Nature Guide', '521-411-5293', 'mclashej@camp.com', '1', '25');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (21, 'Tessie', 'Brobak', 'Lifeguard', '141-167-9382', 'tbrobakk@camp.com', '14', '6');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (22, 'Dur', 'Maidens', 'Arts and Crafts Instructor', '377-311-1247', 'dmaidensl@camp.com', '35', '27');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (23, 'Claiborn', 'Danbi', 'Camp Nurse', '362-636-4434', 'cdanbim@camp.com', '15', '22');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (24, 'Lem', 'Busswell', 'Camp Counselor', '451-318-2342', 'lbusswelln@camp.com', '16', '24');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (25, 'Norean', 'Dugald', 'Kitchen Staff', '837-541-6631', 'ndugaldo@camp.com', '34', '3');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (26, 'Silvester', 'Licas', 'Activity Leader', '717-364-0013', 'slicasp@camp.com', '45', '22');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (27, 'Finn', 'Bru', 'Outdoor Adventure Specialist', '186-983-7074', 'fbruq@camp.com', '31', '22');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (28, 'Son', 'Speller', 'Outdoor Adventure Specialist', '414-996-4521', 'sspellerr@camp.com', '22', '30');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (29, 'Wiatt', 'Eltringham', 'Lifeguard', '612-930-1104', 'weltringhams@camp.com', '44', '34');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (30, 'Juliann', 'McGrirl', 'Activity Leader', '599-473-1702', 'jmcgrirlt@camp.com', '12', '15');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (31, 'Klara', 'D''eath', 'Nature Guide', '304-722-6522', 'kdeathu@camp.com', '11', '4');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (32, 'Rube', 'Snodin', 'Camp Counselor', '440-239-4134', 'rsnodinv@camp.com', '48', '6');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (33, 'Letizia', 'Chown', 'Lifeguard', '630-158-0457', 'lchownw@camp.com', '24', '16');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (34, 'Gerick', 'Ginni', 'Camp Counselor', '838-459-2684', 'gginnix@camp.com', '43', '7');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (35, 'Dody', 'Matkovic', 'Camp Counselor', '872-323-9719', 'dmatkovicy@camp.com', '21', '5');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (36, 'Shaina', 'O''Farrell', 'Outdoor Adventure Specialist', '593-866-5266', 'sofarrellz@camp.com', '26', '24');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (37, 'Lyndsey', 'Wiskar', 'Nature Guide', '285-390-5017', 'lwiskar10@camp.com', '42', '17');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (38, 'Walden', 'Brundell', 'Lifeguard', '415-341-3264', 'wbrundell11@camp.com', '36', '10');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (39, 'Emmit', 'Fellgatt', 'Activity Leader', '858-777-4197', 'efellgatt12@camp.com', '27', '32');
insert into Staff (staffID, firstName, lastName, role, phoneNumber, email, sessionID, campID) values (40, 'Opaline', 'Cessford', 'Camp Photographer', '503-503-2641', 'ocessford13@camp.com', '18', '6');
